apiVersion: v1
kind: ConfigMap
metadata:
  name: overmindv-config
  namespace: overmindv
data:
  USERS_PORT: "8080"
  USERS_GRAPHQL_URL: "http://users:8080/query"
  USERS_HEALTH_URL: "http://users:8080/health"
  USERS_TIMEOUT: "5s"
  ENTITIES_SERVICE_NAME: "entities"
  ENTITIES_HTTP_ADDR: ":8080"
  ENTITIES_LOG_LEVEL: "info"
  ENTITIES_ENV: "kubernetes"
  ENTITIES_URL: "http://entities:8080"
  ENTITIES_TIMEOUT: "5s"
  TASKS_IT_SERVICE_NAME: "tasks-it"
  TASKS_IT_HTTP_ADDR: ":8080"
  TASKS_IT_LOG_LEVEL: "info"
  TASKS_IT_ENV: "kubernetes"
  TASKS_IT_READ_TIMEOUT: "10s"
  TASKS_IT_WRITE_TIMEOUT: "20s"
  TASKS_IT_URL: "http://tasks-it:8080"
  TASKS_IT_TIMEOUT: "5s"
  TASK_HUNTER_URL: "http://task-hunter:8080"
  TASK_HUNTER_TIMEOUT: "10s"
  TASK_HUNTER_CRON: "0 */6 * * *"
  TASK_HUNTER_DEFAULT_LIMIT: "100"
  TASK_HUNTER_CODEFORCES_READER_URL: "https://r.jina.ai/http://codeforces.com"
  TASK_HUNTER_TELEGRAM_ENABLED: "true"
  TASK_HUNTER_TELEGRAM_CHANNELS: "analytic_postupashki,postupashki_ml,algoses"
  API_GATEWAY_PORT: "8081"
  JWT_ISSUER: "users"
  ADMIN_USER_IDS: ""
  JWT_TTL: "24h"
  BOOTSTRAP_SUPERUSER_USERNAME: "superadmin"
  CORS_ORIGINS: "http://overmindv.local"
