apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - ironhide-postgres.yaml
  - ironhide-deployment.yaml
  - ironhide-service.yaml
  - arcee-deployment.yaml
  - arcee-service.yaml
  - laserbeak-deployment.yaml
  - laserbeak-service.yaml
  - soundwave-deployment.yaml
  - soundwave-service.yaml
  - ingress.yaml
