apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - users-postgres.yaml
  - entities-postgres.yaml
  - tasks-it-postgres.yaml
  - task-hunter-postgres.yaml
  - users-deployment.yaml
  - entities-deployment.yaml
  - tasks-it-deployment.yaml
  - task-hunter-deployment.yaml
  - api-gateway-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
