apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcee
  template:
    metadata:
      labels:
        app: arcee
    spec:
      containers:
        - name: arcee
          image: ghcr.io/overmindv/arcee:0.1.0
          ports:
            - containerPort: 8081
            - containerPort: 9091
          env:
            - name: ARCEE_ENV
              value: base
            - name: ARCEE_HTTP_ADDR
              value: :8081
            - name: ARCEE_GRPC_ADDR
              value: :9091
---
apiVersion: v1
kind: Service
metadata:
  name: arcee
spec:
  selector:
    app: arcee
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: grpc
      port: 9091
      targetPort: 9091
