apiVersion: apps/v1
kind: Deployment
metadata:
  name: laserbeak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laserbeak
  template:
    metadata:
      labels:
        app: laserbeak
    spec:
      containers:
        - name: laserbeak
          image: ghcr.io/overmindv/laserbeak:0.1.0
          ports:
            - containerPort: 8080
          env:
            - name: LASERBEAK_ENV
              value: base
            - name: LASERBEAK_HTTP_ADDR
              value: :8080
            - name: ARCEE_GRPC_ADDR
              value: arcee:9091
---
apiVersion: v1
kind: Service
metadata:
  name: laserbeak
spec:
  selector:
    app: laserbeak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
