apiVersion: apps/v1
kind: Deployment
metadata:
  name: soundwave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soundwave
  template:
    metadata:
      labels:
        app: soundwave
    spec:
      containers:
        - name: soundwave
          image: ghcr.io/overmindv/soundwave:0.1.0
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_BASE_URL
              value: http://laserbeak:8080
---
apiVersion: v1
kind: Service
metadata:
  name: soundwave
spec:
  selector:
    app: soundwave
  ports:
    - name: http
      port: 5173
      targetPort: 5173
